apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-db-service
          image: kadekpradnyana/bonsai-user-table
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: MONGO_INITDB_USERNAME
              value: "dekjon"
            - name: MONGO_INITDB_PASSWORD
              value: "Dontlookback"
            - name: MONGO_INITDB_DATABASE
              value: "users"
          ports:
            - containerPort: 27017
        - name: user-service
          image: kadekpradnyana/bonsai-user-mgmt
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: MONGODB_HOST
              value: "mongodb://dekjon:Dontlookback@localhost:27017/users"
          ports:
            - containerPort: 3010
            - containerPort: 4010

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - name: http
      protocol: TCP
      port: 3010
      targetPort: 3010
    - name: rpc
      protocol: TCP
      port: 4010
      targetPort: 4010
